config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'application#index'

  resources :questions do
    resources :answers do
      resources :corrections
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :corrections
end

app/models/correction.rb
class Correction < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
end

app/models/edit.rb
class Edit < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :corrections

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    question = Question.find params[:question_id]
    
    question.answers.create answer_params
    redirect_to root_path
  end

  private
    def answer_params
      params.require(:answer).permit(:text)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
    @questions = Question.all
  end
end

app/controllers/corrections_controller.rb
class CorrectionsController < ApplicationController

  def create
    answer = Answer.find params[:answer_id]

    answer.corrections.create correction_params
    redirect_to root_path
  end

  private
    def correction_params
      params.require(:correction).permit(:text)
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    Question.create question_params
    redirect_to root_path
  end

  private
    def question_params
      params.require(:question).permit(:title, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/new.html.slim
= form_for :answer, url: question_answers_path do |a|
    = a.text_field :text
    = a.submit

app/views/application/index.html.slim
- @questions.each do |q|
  = q.title
  = q.description
  - q.answers.each do |a|
    = a.text
    - a.corrections.each do |e|
      = e.text
    = link_to 'Правка', new_question_answer_correction_path(q.id, a.id)

  = link_to 'Дать ответ', new_question_answer_path(q.id)
  
= link_to 'Задать вопрос', new_question_path

app/views/corrections/new.html.slim
= form_for :correction, url: question_answer_corrections_path do |e|
    = e.text_field :text
    = e.submit

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title QA
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield

app/views/questions/new.html.slim
= form_for :question, url: questions_path do |f|
  p
    = f.label :title
    br
    = f.text_field :title
  p
    = f.label :description
    br
    = f.text_area :description
  p
    = f.submit